import { AudioStorageQueryable } from '../models/audio-storage-queryable.js';
import { TrackSelection } from '../models/sutta-player-state.js';
import { SuttaStorageQueryable } from "../models/sutta-storage-queryable.js";
export declare class SuttaPlayerController {
    static VERSION: string;
    _audioStore: AudioStorageQueryable;
    _suttaStore: SuttaStorageQueryable;
    private _appRoot;
    private _model;
    private _view;
    private _settingsController;
    private _searchController;
    private _fabController;
    private _offlineController;
    private _resetAppController;
    private _aboutController;
    private _lastScrollTime;
    private _lineSelectionCb;
    constructor(appRoot: string, suttaStorage: SuttaStorageQueryable, audioStorage: AudioStorageQueryable);
    setup(): Promise<void>;
    tearDown(): Promise<void>;
    showUserMessage(msg: string, dur?: number): void;
    private _injectVersionInfo;
    private _registerListeners;
    private _registerNavigationListeners;
    private _registerDisplayListeners;
    private _onAudioEnded;
    private _onAlbumSelected;
    private _onTrackSelected;
    _onLoadAudio(srcSel: TrackSelection): Promise<boolean>;
    _onLoadText(srcSel: TrackSelection): Promise<boolean>;
    private _onLineSelected;
    private _onLoadRandom;
    private _onShareLink;
    _onLoadIntoNavSelector(srcSel: TrackSelection): void;
    private _loadShareLinkIfSpecified;
}
