import { TrackSelection } from '../models/album-player-state.js';
import { AlbumStorageQueryable } from "../models/album-storage-queryable.js";
import { DeferredPromise } from '../runtime/deferred-promise.js';
export declare class SuttaPlayerController {
    static VERSION: string;
    _albumStore: AlbumStorageQueryable;
    private _model;
    private _view;
    private _appRoot;
    private _settingsController;
    private _searchController;
    private _fabController;
    private _offlineController;
    private _resetAppController;
    private _aboutController;
    private _lastScrollTime;
    private _lineSelectionCb;
    tabSelectedIndex: number;
    private _tabWndScrollPosMap;
    private _onTabEnter;
    private _onTabExit;
    audDurWait: DeferredPromise<number>;
    audDurWaitState: number;
    constructor(appRoot: string, albumStorage: AlbumStorageQueryable);
    setup(): Promise<void>;
    tearDown(): Promise<void>;
    createAudDurWait(): void;
    showUserMessage(msg: string, dur?: number): void;
    openTab(tabNum: number): void;
    private _injectVersionInfo;
    private _registerListeners;
    private _registerNavigationListeners;
    private _registerDisplayListeners;
    private _onAudioEnded;
    private _onAlbumSelected;
    private _onTrackSelected;
    _onLoadAudio(srcSel: TrackSelection): Promise<void>;
    _onLoadTrack(srcSel: TrackSelection): Promise<boolean>;
    private _onLineSelected;
    private _onSelectRandom;
    private _onShareLink;
    _onRevealInCatalog(srcSel: TrackSelection): Promise<void>;
    private _loadShareLinkIfSpecified;
}
